name: compliance tests

on:
  pull_request:
    branches: [ "ocopt/production" ]


jobs:
  compliance-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5

    - name: Run tests
      run: go test ./...
