name: deploy-dev-ssokenizer
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go test -v ./...

  build-and-push-ssokenizer:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: .github/workflows/build-and-push.yml
    secrets: inherit
    with:
      repo-name: ssokenizer
      content: .

  deploy-ssokenizer:
      needs: build-and-push-ssokenizer
      concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
      uses: .github/workflows/deploy-to-ecs.yml
      secrets: inherit
      with:
        region: ap-southeast-2
        cluster-name: dev
        repo-name: ssokenizer
        task-family: dev-ssokenizer
        service-name: dev-ssokenizer
